"""init

Revision ID: 10fb17efd947
Revises: 
Create Date: 2026-02-16 15:00:32.309839

"""
import sqlmodel

from alembic import op
import sqlalchemy as sa



revision = '10fb17efd947'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('template_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['template_id'], ['product_template_version.id'], ),
                    sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_product_template_id'), 'product', ['template_id'], unique=False)
    op.create_index("uq_product_name_active", "product", [sa.text("lower(name)")], unique=True,
                    sqlite_where=sa.text("deleted_at IS NULL"), postgresql_where=sa.text("deleted_at IS NULL"))

    op.create_table('product_template_version',
                    sa.Column('chart_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('version_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('chart_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('chart_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('default_values_json', sa.JSON(), nullable=True),
                    sa.Column('values_schema_json', sa.JSON(), nullable=True),
                    sa.Column('capabilities_json', sa.JSON(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('health_timeout_sec', sa.Integer(), nullable=True),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
                    sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_product_template_version_product_id'), 'product_template_version', ['product_id'], unique=False)
    op.create_index('uq_producttemplate_active', 'product_template_version', ['chart_ref', 'chart_version', 'product_id'], unique=True,
                    sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text("deleted_at IS NULL"))

    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("uq_user_active", "user", [sa.text("lower(email)")], unique=True,
                    sqlite_where=sa.text("deleted_at IS NULL"), postgresql_where=sa.text("deleted_at IS NULL"))

    op.create_table('deployment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('desired_template_id', sa.Integer(), nullable=False),
                    sa.Column('applied_template_id', sa.Integer(), nullable=True),
                    sa.Column('domainname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('deployment_uid', sa.String(), nullable=False),
                    sa.Column('user_values_json', sa.JSON(), nullable=True),
                    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('generation', sa.Integer(), nullable=False),
                    sa.Column('last_error', sa.Text(), nullable=True),
                    sa.Column('last_reconcile_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['applied_template_id'], ['product_template_version.id'], ),
                    sa.ForeignKeyConstraint(['desired_template_id'], ['product_template_version.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_deployment_applied_template_id'), 'deployment', ['applied_template_id'], unique=False)
    op.create_index(op.f('ix_deployment_deployment_uid'), 'deployment', ['deployment_uid'], unique=False)
    op.create_index(op.f('ix_deployment_desired_template_id'), 'deployment', ['desired_template_id'], unique=False)
    op.create_index(op.f('ix_deployment_domainname'), 'deployment', ['domainname'], unique=False)
    op.create_index(op.f('ix_deployment_status'), 'deployment', ['status'], unique=False)
    op.create_index(op.f('ix_deployment_user_id'), 'deployment', ['user_id'], unique=False)
    op.create_index('uq_deployment_active', 'deployment', ['user_id', 'domainname', 'desired_template_id'], unique=True,
                    sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text("deleted_at IS NULL"))
    op.create_index('uq_domainname_active', 'deployment', [sa.text("lower(domainname)")], unique=True,
                    sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text("deleted_at IS NULL"))

    op.create_table('deployment_reconcile_job',
                    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('run_after', sa.DateTime(), nullable=False),
                    sa.Column('attempt', sa.Integer(), nullable=False),
                    sa.Column('locked_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('locked_at', sa.DateTime(), nullable=True),
                    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('deployment_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_reconcile_job_deployment_id'), 'deployment_reconcile_job', ['deployment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployment_reconcile_job_deployment_id'), table_name='deployment_reconcile_job')
    op.drop_table('deployment_reconcile_job')
    op.drop_index('uq_domainname_active', table_name='deployment', sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_deployment_active', table_name='deployment', sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_deployment_user_id'), table_name='deployment')
    op.drop_index(op.f('ix_deployment_status'), table_name='deployment')
    op.drop_index(op.f('ix_deployment_domainname'), table_name='deployment')
    op.drop_index(op.f('ix_deployment_desired_template_id'), table_name='deployment')
    op.drop_index(op.f('ix_deployment_deployment_uid'), table_name='deployment')
    op.drop_index(op.f('ix_deployment_applied_template_id'), table_name='deployment')
    op.drop_table('deployment')
    op.drop_index('uq_user_active', table_name='user', sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_table('user')
    op.drop_index('uq_producttemplate_active', table_name='product_template_version', sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_product_template_version_product_id'), table_name='product_template_version')
    op.drop_table('product_template_version')
    op.drop_index('uq_product_name_active', table_name='product', sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_product_template_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
