"""init

Revision ID: 7f754e435ae2
Revises: 
Create Date: 2026-02-11 21:25:37.337060

"""
import sqlmodel
import sqlalchemy as sa
from alembic import op


revision = '7f754e435ae2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['product_template_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_index(op.f('ix_product_template_id'), 'product', ['template_id'], unique=False)
    op.create_index('uq_product_name_active', 'product', ['name'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_table('product_template_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docker_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_template_version_product_id'), 'product_template_version', ['product_id'], unique=False)
    op.create_index('uq_producttemplate_active', 'product_template_version', ['docker_image_url', 'product_id'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index('uq_user_active', 'user', ['email'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_table('deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('domainname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['product_template_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_domainname'), 'deployment', ['domainname'], unique=False)
    op.create_index(op.f('ix_deployment_template_id'), 'deployment', ['template_id'], unique=False)
    op.create_index(op.f('ix_deployment_user_id'), 'deployment', ['user_id'], unique=False)
    op.create_index('uq_deployment_active', 'deployment', ['user_id', 'domainname', 'template_id'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_deployment_active', table_name='deployment', sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_deployment_user_id'), table_name='deployment')
    op.drop_index(op.f('ix_deployment_template_id'), table_name='deployment')
    op.drop_index(op.f('ix_deployment_domainname'), table_name='deployment')
    op.drop_table('deployment')
    op.drop_index('uq_user_active', table_name='user', sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index('uq_producttemplate_active', table_name='product_template_version', sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_product_template_version_product_id'), table_name='product_template_version')
    op.drop_table('product_template_version')
    op.drop_index('uq_product_name_active', table_name='product', sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_product_template_id'), table_name='product')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
