"""deployment_deletion

Revision ID: 9b4e729fd792
Revises: 10fb17efd947
Create Date: 2026-02-20 22:20:12.413207

"""
from alembic import op
import sqlalchemy as sa



revision = '9b4e729fd792'
down_revision = '10fb17efd947'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_domainname_active', table_name='deployment')
    op.create_index('uq_domainname_active', 'deployment', ['domainname'], unique=True,
                    sqlite_where=sa.text("status is not 'deleted'"), postgresql_where=sa.text("status is not 'deleted'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_domainname_active', table_name='deployment')
    op.create_index('uq_domainname_active', 'deployment', [sa.text("lower(domainname)")], unique=True,
                    sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text("deleted_at IS NULL"))
    # ### end Alembic commands ###
