from __future__ import annotations

from uuid import UUID

import pytest

from tests.conftest import (
    ADMIN_EMAIL,
    OTHER_AUTH_HEADER,
    USER_AUTH_HEADER,
    create_free_plan_template,
    create_user,
)


def _create_deployment(client, db_session, *, user_id: int) -> str:
    """Create a product + canonical template + deployment for ``user_id``.

    Returns deployment_id. The deployment's namespace/name are generated by the
    create flow; the SFTP endpoint reads a Secret from that namespace, which the
    tests stub at the provisioner boundary.
    """
    product_id = client.post(
        "/api/products", json={"name": "files-app", "description": "app"}
    ).json()["id"]
    template_id = client.post(
        f"/api/products/{product_id}/templates",
        json={
            "chart_ref": "registry.home/files/",
            "chart_version": "1.0.0",
            "values_schema_json": {"type": "object", "properties": {}},
        },
    ).json()["id"]
    client.put(f"/api/products/{product_id}", json={"template_id": template_id})
    ptv_id = create_free_plan_template(db_session, product_id)
    resp = client.post(
        f"/api/users/{user_id}/deployments",
        json={"desired_template_id": template_id, "tos_version": "2026-07-01", "plan_template_id": ptv_id},
    )
    assert resp.status_code == 201
    return resp.json()["deployment"]["id"]


@pytest.fixture
def stub_sftp(monkeypatch):
    """Stub the provisioner's SFTP secret read. Pass creds=None to simulate a
    product that exposes no files (no credentials Secret)."""
    def _install(creds):
        monkeypatch.setattr(
            "app.provisioner.provisioner.read_sftp_credentials",
            lambda **kwargs: creds,
        )
    return _install


def test_owner_gets_sftp_credentials(client, db_session, stub_sftp, monkeypatch):
    monkeypatch.setenv("CAELUS_SFTP_HOST", "dev.freepod.eu")
    monkeypatch.setenv("CAELUS_SFTP_PORT", "23")
    from app.config import get_settings

    get_settings.cache_clear()
    stub_sftp({"username": "files-app-ab12cd", "password": "s3cret-pw"})

    user_id = client.get("/api/me").json()["id"]
    deployment_id = _create_deployment(client, db_session, user_id=user_id)
    resp = client.get(f"/api/users/{user_id}/deployments/{deployment_id}/sftp")

    assert resp.status_code == 200
    body = resp.json()
    assert body == {
        "host": "dev.freepod.eu",
        "port": 23,
        "username": "files-app-ab12cd",
        "password": "s3cret-pw",
    }
    get_settings.cache_clear()


def test_absent_secret_returns_404(client, db_session, stub_sftp):
    stub_sftp(None)  # product exposes no files
    user_id = client.get("/api/me").json()["id"]
    deployment_id = _create_deployment(client, db_session, user_id=user_id)
    resp = client.get(f"/api/users/{user_id}/deployments/{deployment_id}/sftp")
    assert resp.status_code == 404


def test_admin_can_read_other_users_credentials(client, db_session, stub_sftp):
    stub_sftp({"username": "files-app-zz99", "password": "pw"})
    # client is admin; create a deployment owned by a regular user
    regular_id = create_user(client, "owner@example.com")["id"]
    product_id = client.post(
        "/api/products", json={"name": "a", "description": "a"}
    ).json()["id"]
    template_id = client.post(
        f"/api/products/{product_id}/templates",
        json={"chart_ref": "r/", "chart_version": "1.0.0", "values_schema_json": {"type": "object", "properties": {}}},
    ).json()["id"]
    client.put(f"/api/products/{product_id}", json={"template_id": template_id})
    ptv_id = create_free_plan_template(db_session, product_id)
    deployment_id = client.post(
        f"/api/users/{regular_id}/deployments",
        json={"desired_template_id": template_id, "tos_version": "2026-07-01", "plan_template_id": ptv_id},
    ).json()["deployment"]["id"]

    resp = client.get(f"/api/users/{regular_id}/deployments/{deployment_id}/sftp")
    assert resp.status_code == 200


def test_non_owner_is_denied(user_client, db_session, stub_sftp):
    # A regular user requesting another user's deployment is rejected by
    # require_self before any secret is read (same guard as other sub-resources).
    stub_sftp({"username": "u", "password": "p"})
    client, admin_user = user_client
    resp = client.get(
        f"/api/users/{admin_user.id}/deployments/"
        "00000000-0000-0000-0000-000000000000/sftp"
    )
    assert resp.status_code == 403


def test_cli_parity(cli_runner, monkeypatch):
    from tests.test_cli import _seed_deployment_via_services

    runner, cli_app = cli_runner
    monkeypatch.setattr(
        "app.provisioner.provisioner.read_sftp_credentials",
        lambda **kwargs: {"username": "files-app-cli", "password": "cli-pw"},
    )

    user_id, deployment_id = _seed_deployment_via_services()

    result = runner.invoke(cli_app, ["get-deployment-sftp", str(user_id), str(deployment_id)])
    assert result.exit_code == 0, result.output
    assert "files-app-cli" in result.output
    assert "cli-pw" in result.output

    # Absent secret -> stable not-found error, no traceback.
    monkeypatch.setattr(
        "app.provisioner.provisioner.read_sftp_credentials", lambda **kwargs: None
    )
    missing = runner.invoke(cli_app, ["get-deployment-sftp", str(user_id), str(deployment_id)])
    assert missing.exit_code == 1
    assert "Traceback" not in missing.output
