services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=caelus
      - POSTGRES_PASSWORD=caelus
      - POSTGRES_DB=caelus
    ports:
      - "5432:5432"
    volumes:
      - ./var/pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    # Allow Chrome sandboxing:
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    shm_size: "1gb"
    ports:
      - "5173:5173" # ui
      - "8000:8000" # api
      - "8501:8501" # streamlit
    env_file:
      # Must declare DEPRUTSER_API_KEY
      - path: ./.env
        required: false
    environment:
      - CAELUS_DATABASE_URL=postgresql+psycopg://caelus:caelus@postgres:5432/caelus
      - KUBECONFIG=/workspace/k8s/kubeconfigs/dev-k3s.yaml
      # https://github.com/anthropics/claude-code/issues/1736#issuecomment-3170502150
      - CLAUDE_CONFIG_DIR=/home/vscode/.claude
    volumes:
      - .:/workspace
    depends_on:
      - postgres
