{{- if .Values.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-mattermost
  labels:
    app.kubernetes.io/name: mattermost
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ingressClassName: {{ .Values.mattermost.ingress.className }}
  rules:
    - host: {{ .Values.host | quote }}
      http:
        paths:
          - path: {{ .Values.mattermost.ingress.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-mattermost
                port:
                  number: 8065
{{- end }}
