apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mattermost.fullname" . }}-data
  labels:
    app.kubernetes.io/name: mattermost
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mattermost.fullname" . }}-plugins
  labels:
    app.kubernetes.io/name: mattermost
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
