apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mattermost-db
  labels:
    app.kubernetes.io/name: mattermost
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  MM_CONFIG: {{ printf "postgres://%s:%s@%s-postgresql:5432/%s?sslmode=disable&connect_timeout=10" .Values.postgresql.username .Values.postgresql.password .Release.Name .Values.postgresql.database | b64enc | quote }}
