apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "naas.fullname" . }}-images
  labels:
    app.kubernetes.io/name: {{ include "naas.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
binaryData:
  {{- range $path, $bytes := .Files.Glob "static/**" }}
  {{ base $path }}: {{ $.Files.Get $path | b64enc }}
  {{- end }}
