image:
  repository: python
  tag: "3.12-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  annotations: {}
  host: ""

server:
  port: 8080
