apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix.fullname" . }}-headless
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "matrix.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
