apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mattermost.fullname" . }}-db
  labels:
    app.kubernetes.io/name: mattermost
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  MM_CONFIG: {{ printf "postgres://%s:%s@%s:5432/%s?sslmode=disable&connect_timeout=10" .Values.postgresql.username .Values.postgresql.password (include "mattermost.postgresql.fullname" .) .Values.postgresql.database | b64enc | quote }}
