from __future__ import annotations

DEPLOYMENT_STATUS_PENDING = "pending"
DEPLOYMENT_STATUS_PROVISIONING = "provisioning"
DEPLOYMENT_STATUS_READY = "ready"
DEPLOYMENT_STATUS_UPGRADING = "upgrading"
DEPLOYMENT_STATUS_DELETING = "deleting"
DEPLOYMENT_STATUS_DELETED = "deleted"
DEPLOYMENT_STATUS_ERROR = "error"

DEPLOYMENT_STATUSES: tuple[str, ...] = (
    DEPLOYMENT_STATUS_PENDING,
    DEPLOYMENT_STATUS_PROVISIONING,
    DEPLOYMENT_STATUS_READY,
    DEPLOYMENT_STATUS_UPGRADING,
    DEPLOYMENT_STATUS_DELETING,
    DEPLOYMENT_STATUS_DELETED,
    DEPLOYMENT_STATUS_ERROR,
)

JOB_STATUS_QUEUED = "queued"
JOB_STATUS_RUNNING = "running"
JOB_STATUS_DONE = "done"
JOB_STATUS_FAILED = "failed"

JOB_STATUSES: tuple[str, ...] = (
    JOB_STATUS_QUEUED,
    JOB_STATUS_RUNNING,
    JOB_STATUS_DONE,
    JOB_STATUS_FAILED,
)

JOB_REASON_CREATE = "create"
JOB_REASON_UPDATE = "update"
JOB_REASON_DELETE = "delete"
JOB_REASON_DRIFT = "drift"

JOB_REASONS: tuple[str, ...] = (
    JOB_REASON_CREATE,
    JOB_REASON_UPDATE,
    JOB_REASON_DELETE,
    JOB_REASON_DRIFT,
)
